#
# adobe_scanner-config.yaml
#
# configure the adobe umapi-client  (see Adobe documentation for details).
# https://github.com/adobe-apiplatform/umapi-documentation
#
org_id: ...@AdobeOrg
tech_acct_id: ....@techacct.adobe.com
# some Adobe docs refer to the api_key as client_id
api_key: ....
client_secret: ....
# private key file in pem format
private_key_file: c:/Tools/Cert/acme_private.pem




